# Generated by Django 5.1.2 on 2024-10-27 05:04

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field="height_field",
                        null=True,
                        upload_to=account.models.upload_location,
                        width_field="width_field",
                    ),
                ),
                ("height_field", models.IntegerField(default=0)),
                ("width_field", models.IntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "male"),
                            ("F", "female"),
                            ("T", "transgendered"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=30)),
                ("pin_code", models.CharField(blank=True, max_length=6)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timeStamps", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
